server:
  port: 8081

spring:
  application:
    name: anqhv-personajes-service
  datasource:
    url: jdbc:postgresql://localhost:5432/anhqv_character_db
    username: anhqv_user
    password: anhqv_password
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka